stages:
  - lint
  - test
  - coverage
  - build
  - push
  - meta

variables:
  CARGO_TERM_COLOR: always
  CI_REGISTRY: registry.gitlab.com
  CI_REGISTRY_IMAGE: registry.gitlab.com/ponb/stripe-slinger
  CI_RUST_IMAGE: "$CI_REGISTRY_IMAGE/ci:rust-1.85"
  RUSTFLAGS: "-C debuginfo=2"

.rust-changes:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^feature\//'
      changes:
        - "**/*.rs"
        - "**/Cargo.toml"
        - "**/Cargo.lock"
        - Dockerfile
        - .gitlab-ci.yml

default:
  image: $CI_RUST_IMAGE
  tags:
    - docker
  interruptible: true
  cache:
    key: "rust-${CI_COMMIT_REF_SLUG}"
    policy: pull-push
    paths:
      - target
      - .cargo/registry
      - .cargo/git
  before_script:
    - rustc --version
    - cargo --version
