name: No Code Gate

on:
  workflow_call:

permissions:
  contents: read

jobs:
  no-code-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: .gitlab/ci/shared/scripts/no-code-gate.sh
